import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | tutorial",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "20px", background: "gray" }}>header</header>
        <main>{children}</main>
        <footer style={{ padding: "20px", background: "cyan" }}>footer</footer>
      </body>
    </html>
  );
}
