export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "20px", background: "gray" }}>header</header>
        <main>{children}</main>
        <footer style={{ padding: "20px", background: "cyan" }}>footer</footer>
      </body>
    </html>
  );
}
